table peers
	lineageTag: bbe36b20-974b-4212-9320-4a80b372d44c

	measure 'Peer Institutions' = COUNTROWS ( peers )
		formatString: #,0
		lineageTag: dbe7fdec-4e6f-438d-977c-85cb78038e29

	measure 'Peer Groups' = DISTINCTCOUNT ( peers[peer_group] )
		formatString: #,0
		lineageTag: 113ad663-bcbe-492a-9d39-f4363374b7b8

	measure 'Peer Median Pell' = MEDIAN ( peers[pct_pell] )
		formatString: 0.0"%"
		lineageTag: dc6026d3-e418-4133-891f-5a2bfb46f3b9

	measure 'Peer Median Completion' = MEDIAN ( peers[grad_rate_bach_6yr] )
		formatString: 0.0"%"
		lineageTag: 1b9b1977-3312-4d50-be92-5d419b15a922

	measure 'Peer Median Net Price' = MEDIAN ( peers[net_price] )
		formatString: $#,0
		lineageTag: babf4aea-af39-4634-af84-56799ef7396b

	measure 'Peer Median Retention' = MEDIAN ( peers[retention_ft] )
		formatString: 0.0"%"
		lineageTag: 7d6c230a-d1c7-4d96-96b4-14f1dbad0f65

	measure 'Peer Median Student Faculty Ratio' = MEDIAN ( peers[stu_fac_ratio] )
		formatString: 0.0
		lineageTag: 4dc992c4-48cc-47a0-af85-cda4b19d371b

	/// Unique identification number of the institution | HD2023 | UNITID
	column unitid
		dataType: int64
		isKey
		formatString: #,0
		lineageTag: 3677fe46-9021-4f88-992f-fe1d3754bbef
		summarizeBy: none
		sourceColumn: unitid

	/// Institution name | HD2023 | INSTNM
	column name
		dataType: string
		lineageTag: 7ec76f02-dcda-47b3-9183-375cc43aadb3
		summarizeBy: none
		sourceColumn: name

	/// City location of institution | HD2023 | CITY
	column city
		dataType: string
		lineageTag: 3ead1f12-8558-419c-82b2-b3a04c75a746
		summarizeBy: none
		sourceColumn: city

	/// State abbreviation | HD2023 | STABBR
	column state
		dataType: string
		lineageTag: 3ca6608d-58e1-4ec3-8a46-55184b2dbe4e
		summarizeBy: none
		sourceColumn: state

	/// Bureau of Economic Analysis region | HD2023 | OBEREG
	column region
		dataType: string
		lineageTag: b9ce8cbb-6e6e-4a1c-8d54-03261756a34a
		summarizeBy: none
		sourceColumn: region

	/// Sector of institution (control x level) | HD2023 | SECTOR
	column sector
		dataType: string
		lineageTag: 8210af88-9a88-4536-8961-ab814723fd92
		summarizeBy: none
		sourceColumn: sector

	/// Control of institution | HD2023 | CONTROL
	column control
		dataType: string
		lineageTag: bac035da-f95c-4392-be56-736a7c15c3f5
		summarizeBy: none
		sourceColumn: control

	/// Level of institution | HD2023 | ICLEVEL
	column level
		dataType: string
		lineageTag: abb47c71-635e-4422-8e69-88e3a7a97e12
		summarizeBy: none
		sourceColumn: level

	/// Degree of urbanization, grouped to City, Suburb, Town, Rural | HD2023 | LOCALE
	column locale
		dataType: string
		lineageTag: e5164dc1-e3e4-4e9c-86dd-699a681061bc
		summarizeBy: none
		sourceColumn: locale

	/// Institution size category (fall headcount) | HD2023 | INSTSIZE
	column size
		dataType: string
		lineageTag: 346a3466-f8ec-4ae1-8ab3-02bd552e71e6
		summarizeBy: none
		sourceColumn: size

	/// Carnegie Classification 2021: Basic, grouped | HD2023 | C21BASIC
	column carnegie
		dataType: string
		lineageTag: 8c3fed1d-c40d-4ced-b7df-be75b1246f93
		summarizeBy: none
		sourceColumn: carnegie

	/// Historically Black College or University | HD2023 | HBCU
	column hbcu
		dataType: string
		lineageTag: c9a44200-1b4a-4e43-a8a3-2de3ccffc463
		summarizeBy: none
		sourceColumn: hbcu

	/// Tribal college | HD2023 | TRIBAL
	column tribal
		dataType: string
		lineageTag: 75e86206-da81-4c25-86ee-dfb41196b57a
		summarizeBy: none
		sourceColumn: tribal

	/// Longitude location of institution | HD2023 | LONGITUD
	column longitude
		dataType: double
		lineageTag: 0d2eb5b5-9dea-4800-8b38-c4c30c83689b
		summarizeBy: none
		sourceColumn: longitude

	/// Latitude location of institution | HD2023 | LATITUDE
	column latitude
		dataType: double
		lineageTag: ab996943-f5e6-4f51-9dcf-6af6d10b7e20
		summarizeBy: none
		sourceColumn: latitude

	/// 12-month unduplicated headcount, all students | EFFY2023 | EFYTOTLT (EFFYALEV=1)
	column headcount
		dataType: int64
		formatString: #,0
		lineageTag: b22ab388-1e39-4366-9a07-40e2509c557e
		summarizeBy: none
		sourceColumn: headcount

	/// 12-month unduplicated headcount, undergraduate | EFFY2023 | EFYTOTLT (EFFYALEV=2)
	column undergrad
		dataType: int64
		formatString: #,0
		lineageTag: ebf4a283-1a75-43bb-bd07-53f536a7c63c
		summarizeBy: none
		sourceColumn: undergrad

	/// Percent of undergraduates who are women | EFFY2023 | EFYTOTLW / EFYTOTLT
	column pct_women_ug
		dataType: double
		formatString: 0.0"%"
		lineageTag: af723b30-2849-4ce5-bcb8-7ca33d31d430
		summarizeBy: none
		sourceColumn: pct_women_ug

	/// Percent of undergraduates who are White | EFFY2023 | EFYWHITT / EFYTOTLT
	column pct_white_ug
		dataType: double
		formatString: 0.0"%"
		lineageTag: de75ca9c-9334-49f6-839b-93c51bf8aebb
		summarizeBy: none
		sourceColumn: pct_white_ug

	/// Percent of undergraduates who are Black or African American | EFFY2023 | EFYBKAAT / EFYTOTLT
	column pct_black_ug
		dataType: double
		formatString: 0.0"%"
		lineageTag: 75b0e0da-d8cd-46bd-9525-dcd66822556c
		summarizeBy: none
		sourceColumn: pct_black_ug

	/// Percent of undergraduates who are Hispanic or Latino | EFFY2023 | EFYHISPT / EFYTOTLT
	column pct_hispanic_ug
		dataType: double
		formatString: 0.0"%"
		lineageTag: bd51b479-1c99-469a-ad62-8d5c83e9bc94
		summarizeBy: none
		sourceColumn: pct_hispanic_ug

	/// Percent of undergraduates who are Asian | EFFY2023 | EFYASIAT / EFYTOTLT
	column pct_asian_ug
		dataType: double
		formatString: 0.0"%"
		lineageTag: 5b037169-433d-4317-bdc7-165bf1845b04
		summarizeBy: none
		sourceColumn: pct_asian_ug

	/// Percent of undergraduates who are U.S. nonresidents | EFFY2023 | EFYNRALT / EFYTOTLT
	column pct_intl_ug
		dataType: double
		formatString: 0.0"%"
		lineageTag: 66a2ad8f-e766-4490-95bf-de9d3540cb37
		summarizeBy: none
		sourceColumn: pct_intl_ug

	/// Full-time retention rate, fall 2022 to fall 2023 | EF2023D | RET_PCF
	column retention_ft
		dataType: double
		formatString: 0.0"%"
		lineageTag: eb982085-8832-410e-9d0a-668ec66d8a58
		summarizeBy: none
		sourceColumn: retention_ft

	/// Part-time retention rate, fall 2022 to fall 2023 | EF2023D | RET_PCP
	column retention_pt
		dataType: double
		formatString: 0.0"%"
		lineageTag: 1459d3cf-8f0a-4ed2-a391-14f4284da5dc
		summarizeBy: none
		sourceColumn: retention_pt

	/// Student-to-faculty ratio | EF2023D | STUFACR
	column stu_fac_ratio
		dataType: int64
		formatString: #,0
		lineageTag: 1308e04e-c151-4234-9aa6-59fd6c8456fb
		summarizeBy: none
		sourceColumn: stu_fac_ratio

	/// Adjusted cohort, all degree/certificate-seeking students | GR2023 | GRTOTLT (GRTYPE=2 or 29)
	column grad_cohort
		dataType: int64
		formatString: #,0
		lineageTag: abaee94e-1e14-440a-9204-ce54f23ee864
		summarizeBy: none
		sourceColumn: grad_cohort

	/// Graduation rate within 150% of normal time, all students | GR2023 | GRTYPE 3/2 or 30/29
	column grad_rate_150
		dataType: double
		formatString: 0.0"%"
		lineageTag: 58a38706-5043-4358-a9c4-d0879ddf08cc
		summarizeBy: none
		sourceColumn: grad_rate_150

	/// Adjusted cohort, bachelor's-seeking subcohort at 4-year institutions | GR2023 | GRTOTLT (GRTYPE=8)
	column bach_cohort
		dataType: int64
		formatString: #,0
		lineageTag: bf5fb843-05a5-4f77-a811-e589894ef3b5
		summarizeBy: none
		sourceColumn: bach_cohort

	/// Bachelor's degree completion within 6 years | GR2023 | GRTYPE 12/8
	column grad_rate_bach_6yr
		dataType: double
		formatString: 0.0"%"
		lineageTag: f477f6dd-7871-4d38-81c2-0c3c3de1dade
		summarizeBy: none
		sourceColumn: grad_rate_bach_6yr

	/// Bachelor's degree completion within 4 years | GR2023 | GRTYPE 13/8
	column grad_rate_bach_4yr
		dataType: double
		formatString: 0.0"%"
		lineageTag: 2d16bc80-68b0-431b-b2a8-36628ec4bc64
		summarizeBy: none
		sourceColumn: grad_rate_bach_4yr

	/// Full-time first-time degree-seeking undergraduates in the aid cohort | SFA2223 | SCUGFFN
	column aid_cohort
		dataType: int64
		formatString: #,0
		lineageTag: d487864a-d16e-4170-b2ec-bdfe3d3b0573
		summarizeBy: none
		sourceColumn: aid_cohort

	/// Percent of undergraduates awarded Pell grants | SFA2223 | UPGRNTP
	column pct_pell
		dataType: double
		formatString: 0.0"%"
		lineageTag: dcc36c0e-e7fb-488b-bd1c-328724a8a38f
		summarizeBy: none
		sourceColumn: pct_pell

	/// Percent of undergraduates awarded any grant aid | SFA2223 | UAGRNTP
	column pct_any_grant
		dataType: double
		formatString: 0.0"%"
		lineageTag: 2361e988-437b-4e1f-9728-ff2e5c1ff566
		summarizeBy: none
		sourceColumn: pct_any_grant

	/// Average net price for students awarded grant aid, 2022-23 (in-state at publics) | SFA2223 | NPIST2 or NPGRN2
	column net_price
		dataType: int64
		formatString: $#,0
		lineageTag: 06c43a58-8c84-4f9d-9872-c1e48fc8649a
		summarizeBy: none
		sourceColumn: net_price

	/// Average net price, family income $0-30,000 | SFA2223 | NPT412 or NPIS412
	column net_price_0_30k
		dataType: int64
		formatString: $#,0
		lineageTag: e2113655-71a7-45df-ae00-b45579efec3e
		summarizeBy: none
		sourceColumn: net_price_0_30k

	/// Average net price, family income $30,001-48,000 | SFA2223 | NPT422 or NPIS422
	column net_price_30_48k
		dataType: int64
		formatString: $#,0
		lineageTag: 54f375e2-8925-45df-bc01-311d502c8600
		summarizeBy: none
		sourceColumn: net_price_30_48k

	/// Average net price, family income $48,001-75,000 | SFA2223 | NPT432 or NPIS432
	column net_price_48_75k
		dataType: int64
		formatString: $#,0
		lineageTag: eddf8fc9-f9a5-4adf-9504-6847e4c555ef
		summarizeBy: none
		sourceColumn: net_price_48_75k

	/// Average net price, family income $75,001-110,000 | SFA2223 | NPT442 or NPIS442
	column net_price_75_110k
		dataType: int64
		formatString: $#,0
		lineageTag: 5075e711-8b1e-4a2e-9cb3-ff50dfcb225a
		summarizeBy: none
		sourceColumn: net_price_75_110k

	/// Average net price, family income $110,001 or more | SFA2223 | NPT452 or NPIS452
	column net_price_110k_plus
		dataType: int64
		formatString: $#,0
		lineageTag: f18766a9-c808-41d7-9bec-f336c6af0604
		summarizeBy: none
		sourceColumn: net_price_110k_plus

	/// Associate's degrees awarded, 2022-23 | C2023_C | CSTOTLT (AWLEVELC=3)
	column associates_awarded
		dataType: int64
		formatString: #,0
		lineageTag: 9d8cd1ff-72a5-4321-88cd-3b7727cc8cfa
		summarizeBy: none
		sourceColumn: associates_awarded

	/// Bachelor's degrees awarded, 2022-23 | C2023_C | CSTOTLT (AWLEVELC=5)
	column bachelors_awarded
		dataType: int64
		formatString: #,0
		lineageTag: 91b8a844-4f0d-49c1-998c-ff2161a3906f
		summarizeBy: none
		sourceColumn: bachelors_awarded

	/// Master's degrees awarded, 2022-23 | C2023_C | CSTOTLT (AWLEVELC=7)
	column masters_awarded
		dataType: int64
		formatString: #,0
		lineageTag: c95908ad-3e08-4296-aae9-49daa66681d9
		summarizeBy: none
		sourceColumn: masters_awarded

	/// Doctor's degrees awarded, 2022-23 | C2023_C | CSTOTLT (AWLEVELC=9)
	column doctorates_awarded
		dataType: int64
		formatString: #,0
		lineageTag: 0b893155-244b-4e1c-8ec3-15a64071dedf
		summarizeBy: none
		sourceColumn: doctorates_awarded

	/// peer_group
	column peer_group
		dataType: string
		lineageTag: cef6e974-01b6-480c-aec3-168b48fc2f8a
		summarizeBy: none
		sourceColumn: peer_group
		sortByColumn: peer_group_sort

	/// peer_group_sort
	column peer_group_sort
		dataType: int64
		formatString: #,0
		lineageTag: 66e8c451-148b-4c25-b814-8b113ae6658e
		summarizeBy: none
		sourceColumn: peer_group_sort

	partition peers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ProjectRoot & "/powerbi/data/peers.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Nulls = Table.ReplaceValue(Headers, "", null, Replacer.ReplaceValue, Table.ColumnNames(Headers)),
				    Typed = Table.TransformColumnTypes(Nulls, {{"unitid", Int64.Type}, {"name", type text}, {"city", type text}, {"state", type text}, {"region", type text}, {"sector", type text}, {"control", type text}, {"level", type text}, {"locale", type text}, {"size", type text}, {"carnegie", type text}, {"hbcu", type text}, {"tribal", type text}, {"longitude", type number}, {"latitude", type number}, {"headcount", Int64.Type}, {"undergrad", Int64.Type}, {"pct_women_ug", type number}, {"pct_white_ug", type number}, {"pct_black_ug", type number}, {"pct_hispanic_ug", type number}, {"pct_asian_ug", type number}, {"pct_intl_ug", type number}, {"retention_ft", type number}, {"retention_pt", type number}, {"stu_fac_ratio", Int64.Type}, {"grad_cohort", Int64.Type}, {"grad_rate_150", type number}, {"bach_cohort", Int64.Type}, {"grad_rate_bach_6yr", type number}, {"grad_rate_bach_4yr", type number}, {"aid_cohort", Int64.Type}, {"pct_pell", type number}, {"pct_any_grant", type number}, {"net_price", Int64.Type}, {"net_price_0_30k", Int64.Type}, {"net_price_30_48k", Int64.Type}, {"net_price_48_75k", Int64.Type}, {"net_price_75_110k", Int64.Type}, {"net_price_110k_plus", Int64.Type}, {"associates_awarded", Int64.Type}, {"bachelors_awarded", Int64.Type}, {"masters_awarded", Int64.Type}, {"doctorates_awarded", Int64.Type}, {"peer_group", type text}, {"peer_group_sort", Int64.Type}}, "en-US")
				in
				    Typed

